In [ ]:
25 - 11 - 2023
# IPL Hackathon

In [2]:
import math
import numpy as np
import pandas as pd

In [10]:
# Set the option to display all columns
pd.set_option('display.max_columns', None)

In [21]:
matches = pd.read_csv("matches.csv")
matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [22]:
deliveries = pd.read_csv("deliveries.csv")
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,2,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,0,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,0,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [8]:
#

In [9]:
# Concatenate along rows (stacking vertically)
ipl = pd.concat([matches, deliveries], axis=0, ignore_index=True)

# Concatenate along columns (stacking horizontally)
ipl = pd.concat([matches, deliveries], axis=1)

In [10]:
ipl

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1.0,2017.0,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0.0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,2.0,2017.0,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,3.0,2017.0,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0.0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,4.0,2017.0,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0.0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,5.0,2017.0,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0.0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [23]:
# Concatenate along columns (stacking horizontally)
ipl = pd.concat([matches, deliveries], axis=1)
ipl

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1.0,2017.0,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0.0,Sunrisers Hyderabad,35.0,0.0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
1,2.0,2017.0,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,Rising Pune Supergiant,0.0,7.0,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
2,3.0,2017.0,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0.0,Kolkata Knight Riders,0.0,10.0,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN
3,4.0,2017.0,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0.0,Kings XI Punjab,0.0,6.0,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
4,5.0,2017.0,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0.0,Royal Challengers Bangalore,15.0,0.0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,2,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,0,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,0,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [ ]:
# Dropping NaN values

In [18]:
ipl = ipl.dropna()

In [19]:
ipl

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
750,11346.0,2019.0,Mohali,05/05/19,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,field,normal,0.0,Kings XI Punjab,0.0,6.0,KL Rahul,IS Bindra Stadium,KN Ananthapadmanabhan,C Shamshuddin,Bruce Oxenford,4,1,Rising Pune Supergiant,Kings XI Punjab,7,2,AM Rahane,SPD Smith,T Natarajan,0,0,0,0,0,0,0,0,0,AM Rahane,caught,MP Stoinis

In [ ]:
# Finding missing values

In [64]:
ipl.isnull().sum()

id                  178322
season              178322
city                178329
date                178322
team1               178322
team2               178322
toss_winner         178322
toss_decision       178322
result              178322
dl_applied          178322
winner              178326
win_by_runs         178322
win_by_wickets      178322
player_of_match     178326
venue               178322
umpire1             178324
umpire2             178324
umpire3             178959
match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [ ]:
# Which city hosted more matches

In [12]:
city_season_counts = matches['city'].value_counts()
city_season_counts

Mumbai            101
Kolkata            77
Delhi              74
Bangalore          66
Hyderabad          64
Chennai            57
Jaipur             47
Chandigarh         46
Pune               38
Durban             15
Bengaluru          14
Visakhapatnam      13
Centurion          12
Ahmedabad          12
Rajkot             10
Mohali             10
Indore              9
Dharamsala          9
Johannesburg        8
Cuttack             7
Ranchi              7
Port Elizabeth      7
Cape Town           7
Abu Dhabi           7
Sharjah             6
Raipur              6
Kochi               5
Kanpur              4
Nagpur              3
Kimberley           3
East London         3
Bloemfontein        2
Name: city, dtype: int64

In [ ]:
# Most matches played by year

In [13]:
matches['season'].value_counts()

2013    76
2012    74
2011    73
2010    60
2014    60
2016    60
2018    60
2019    60
2017    59
2015    59
2008    58
2009    57
Name: season, dtype: int64

In [ ]:
# Most matches won by Mumbai Indians in the year 2011

In [17]:
mi_2011 = matches[(matches['winner'] == 'Mumbai Indians') & (matches['season'] == 2011)]
mi_2011

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
237,238,2011,Delhi,2011-04-10,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,bat,normal,0,Mumbai Indians,0,8,SL Malinga,Feroz Shah Kotla,AM Saheba,RB Tiffin,NaN
241,242,2011,Bangalore,2011-04-12,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,SR Tendulkar,M Chinnaswamy Stadium,HDPK Dharmasena,AL Hill,NaN
253,254,2011,Mumbai,2011-04-20,Pune Warriors,Mumbai Indians,Pune Warriors,bat,normal,0,Mumbai Indians,0,7,MM Patel,Wankhede Stadium,Asad Rauf,AM Saheba,NaN
256,257,2011,Mumbai,2011-04-22,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Mumbai Indians,8,0,Harbhajan Singh,Wankhede Stadium,Asad Rauf,AM Saheba,NaN
259,260,2011,Hyderabad,2011-04-24,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,normal,0,Mumbai Indians,37,0,SL Malinga,"Rajiv Gandhi International Stadium, Uppal",HDPK Dharmasena,AL Hill,NaN
272,273,2011,Mumbai,2011-05-02,Mumbai Indians,Kings XI Punjab,Kings XI Punjab,field,normal,0,Mumbai Indians,23,0,KA Pollard,Wankhede Stadium,HDPK Dharmasena,PR Reiffel,NaN
276,277,2011,Mumbai,2011-05-04,Mumbai Indians,Pune Warriors,Pune Warriors,field,normal,0,Mumbai Indians,21,0,R Sharma,Dr DY Patil Sports Academy,HDPK Dharmasena,SJA Taufel,NaN
281,282,2011,Mumbai,2011-05-07,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,32,0,AT Rayudu,Wankhede Stadium,K Hariharan,SJA Taufel,NaN
302,303,2011,Kolkata,2011-05-22,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,5,JEC Franklin,Eden Gardens,SK Tarapore,SJA Taufel,NaN
304,305,2011,Mumbai,2011-05-25,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,MM Patel,Wankhede Stadium,Asad Rauf,SJA Taufel,NaN

In [68]:
mi_2011['season'].count()

10

In [ ]:
# Toss decision percentage

In [20]:
decision_percentage = matches['toss_decision'].value_counts(normalize=True) * 100
decision_percentage

field    61.243386
bat      38.756614
Name: toss_decision, dtype: float64

In [ ]:
# Winner by toss decision

In [22]:
# Calculate the number of matches won by teams based on toss decision
matches_won_by_fielding = matches[matches['toss_decision'] == 'field']['winner'].value_counts()
matches_won_by_batting = matches[matches['toss_decision'] == 'bat']['winner'].value_counts()

# Calculate the total matches won by each team
total_matches_won = matches['winner'].value_counts()

# Calculate the winning percentage for each decision
percentage_won_by_fielding = matches_won_by_fielding / total_matches_won
percentage_won_by_batting = matches_won_by_batting / total_matches_won

# Display the results
print("Percentage of matches won by choosing to field first:")
print(percentage_won_by_fielding)

print("\nPercentage of matches won by choosing to bat first:")
print(percentage_won_by_batting)

Percentage of matches won by choosing to field first:
Chennai Super Kings            0.480000
Deccan Chargers                0.517241
Delhi Capitals                 0.800000
Delhi Daredevils               0.567164
Gujarat Lions                  0.846154
Kings XI Punjab                0.743902
Kochi Tuskers Kerala           1.000000
Kolkata Knight Riders          0.619565
Mumbai Indians                 0.587156
Pune Warriors                  0.250000
Rajasthan Royals               0.546667
Rising Pune Supergiant         1.000000
Rising Pune Supergiants        0.600000
Royal Challengers Bangalore    0.690476
Sunrisers Hyderabad            0.637931
Name: winner, dtype: float64

Percentage of matches won by choosing to bat first:
Chennai Super Kings            0.520000
Deccan Chargers                0.482759
Delhi Capitals                 0.200000
Delhi Daredevils               0.432836
Gujarat Lions                  0.153846
Kings XI Punjab                0.256098
Kochi Tuskers Kerala                NaN
Kolkata Knight Riders          0.380435
Mumbai Indians                 0.412844
Pune Warriors                  0.750000
Rajasthan Royals               0.453333
Rising Pune Supergiant              NaN
Rising Pune Supergiants        0.400000
Royal Challengers Bangalore    0.309524
Sunrisers Hyderabad            0.362069
Name: winner, dtype: float64

In [ ]:
# Years where taking batting second won more matches

In [24]:
# Filter data for matches where batting second won
batting_second_wins = matches[matches['toss_decision'] == 'field']['season'].value_counts()

# Display the years with more matches won by batting second
print("Years where taking batting second won more matches:")
print(batting_second_wins)

Years where taking batting second won more matches:
2018    50
2019    50
2016    49
2017    48
2011    48
2014    41
2012    37
2015    34
2008    32
2013    31
2009    22
2010    21
Name: season, dtype: int64

In [ ]:
# Batsman with more 4's and 6's

In [46]:
# Create a new column 'runs_through_boundaries' by adding the runs scored through 4's and 6's
df_2019['runs_through_boundaries'] = 4 * df_2019['fours'] + 6 * df_2019['sixes']

# Group by batsman and calculate the total runs through boundaries for each batsman
total_runs_by_boundaries = df_2019.groupby('batsman')['runs_through_boundaries'].sum().reset_index()

# Find the batsman with the highest runs through boundaries
highest_runs_batsman = total_runs_by_boundaries.loc[total_runs_by_boundaries['runs_through_boundaries'].idxmax()]

# Display the result
print(f"In the 2019 IPL season, the batsman who scored the highest number of runs through boundaries is {highest_runs_batsman['batsman']} with {highest_runs_batsman['runs_through_boundaries']} runs.")

KeyError: 'fours'

In [ ]:
# Bowler who took most wickets

In [25]:
# Group by bowler and sum the number of wickets
total_wickets_by_bowler = ipl.groupby('bowler')['player_dismissed'].sum()

# Find the bowler with the most wickets
most_wickets_bowler = total_wickets_by_bowler.idxmax()
most_wickets = total_wickets_by_bowler.max()

print(f"The bowler who took the most number of wickets is {most_wickets_bowler} with {most_wickets} wickets.")

TypeError: reduction operation 'argmax' not allowed for this dtype

In [24]:
ipl

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1.0,2017.0,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0.0,Sunrisers Hyderabad,35.0,0.0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
1,2.0,2017.0,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,Rising Pune Supergiant,0.0,7.0,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
2,3.0,2017.0,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0.0,Kolkata Knight Riders,0.0,10.0,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN
3,4.0,2017.0,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0.0,Kings XI Punjab,0.0,6.0,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
4,5.0,2017.0,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0.0,Royal Challengers Bangalore,15.0,0.0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,2,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,0,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,0,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [72]:
total_wickets_by_bowler = ipl.groupby('bowler')['dismissal_kind'].sum()
total_wickets_by_bowler

bowler
A Ashish Reddy    bowledcaughtcaughtcaughtcaughtlbwlbwbowledcaug...
A Chandila        caughtstumpedstumpedcaught and bowledcaught an...
A Choudhary                          caughtcaughtcaughtcaughtcaught
A Dananjaya                                                       0
A Flintoff                                  caughtcaught and bowled
                                        ...
YA Abdulla        bowledcaughtcaughtcaughtcaughtbowledbowledlbwc...
YK Pathan         caughtstumpedcaughtrun outcaughtcaughtbowledru...
YS Chahal         caughtbowledbowledcaughtcaughtcaughtcaughtstum...
Yuvraj Singh      run outcaughtbowledcaughtcaughtcaughtbowledlbw...
Z Khan            caughtrun outcaughtcaughtcaughtcaughtcaughtcau...
Name: dismissal_kind, Length: 405, dtype: object

In [73]:
ipl['dismissal_kind'].value_counts()

caught                   5348
bowled                   1581
run out                   852
lbw                       540
stumped                   278
caught and bowled         211
retired hurt               12
hit wicket                 10
obstructing the field       2
Name: dismissal_kind, dtype: int64

In [ ]:
# Strike rate of Kholi in 2016

In [19]:
# Filter data for Kohli in 2016
kohli_2016 = ipl[(ipl['batsman'] == 'V Kohli') & (ipl['season'] == 2016)]

# Calculate the total runs and total balls faced
total_runs = kohli_2016['total_runs'].sum()
total_balls_faced = kohli_2016['ball'].sum()

# Calculate the strike rate
strike_rate = (total_runs / total_balls_faced) * 100

print(f"The strike rate of Kohli in 2016 is: {strike_rate:.2f}")

The strike rate of Kohli in 2016 is: nan

C:\Users\rjsek\AppData\Local\Temp\ipykernel_24176\1846715034.py:9: RuntimeWarning: invalid value encountered in longlong_scalars
  strike_rate = (total_runs / total_balls_faced) * 100

In [18]:
balls = ipl['ball'] & ipl[(ipl['batsman'] == 'V Kohli')]
balls

MemoryError:

In [ ]:
# Bowlers with max number of extras

In [15]:
# Group by bowler and calculate the total extras conceded by each bowler
extras_by_bowler = ipl.groupby('bowler')['legbye_runs'].sum().reset_index()

# Find the bowler(s) with the maximum extras
max_extras_bowler = extras_by_bowler[extras_by_bowler['legbye_runs'] == extras_by_bowler['legbye_runs'].max()]

# Print the result
print("Bowler(s) with the maximum number of extras:")
print(max_extras_bowler)

Bowler(s) with the maximum number of extras:
         bowler  legbye_runs
340  SL Malinga           88

In [ ]:
# Number of matches played more in a venue

In [24]:
# Group by venue and count the number of matches at each venue
venue_matches_count = ipl['venue'].value_counts().reset_index()

# Rename the columns for clarity
venue_matches_count.columns = ['venue', 'match_id']

# Display the venue with the most matches
most_matches_venue = venue_matches_count.iloc[0]
print(f"The venue that has hosted the most number of IPL matches is {most_matches_venue['venue']} with {most_matches_venue['match_id']} matches.")

The venue that has hosted the most number of IPL matches is Eden Gardens with 77 matches.

In [ ]:
# Man of the match in SRH vs RCB

In [27]:
# Filter the dataset for the match between Sunrisers Hyderabad and Royal Challengers Bangalore in 2017
match_filter = (ipl['team1'] == 'Sunrisers Hyderabad') & (ipl['team2'] == 'Royal Challengers Bangalore') & (ipl['season'] == 2017)
specific_match_df = ipl[match_filter]

# Get the Player of the Match for that specific match
player_of_the_match = specific_match_df['player_of_match'].values[0]

# Display the result
print(f"In the 2017 IPL match between Sunrisers Hyderabad and Royal Challengers Bangalore, the Player of the Match was {player_of_the_match}.")

In the 2017 IPL match between Sunrisers Hyderabad and Royal Challengers Bangalore, the Player of the Match was Yuvraj Singh.

In [ ]:
# Top 3 batsmen with most run outs

In [31]:
# Filter the dataset for run-out dismissals
run_outs_df = ipl[ipl['dismissal_kind'] == 'run out']

# Group by batsman and count the number of run-outs for each batsman
run_out_counts = run_outs_df['batsman'].value_counts().reset_index()

# Rename the columns for clarity
run_out_counts.columns = ['batsman', 'run out']

# Display the top three batsmen with the most run-outs
top_three_run_outs = run_out_counts.head(5)
print("Top three batsmen with the most run-outs across seasons:")
print(top_three_run_outs)

Top three batsmen with the most run-outs across seasons:
      batsman  run out
0    MS Dhoni       21
1   RG Sharma       17
2  KD Karthik       16
3   G Gambhir       15
4     V Kohli       15

In [ ]:
# Runs scored by V Kohli

In [32]:
# Filter the dataset for matches where the bowler was JJ Bumrah and batsman was V Kohli
filtered_df = ipl[(ipl['bowler'] == 'JJ Bumrah') & (ipl['batsman'] == 'V Kohli')]

# Calculate the total runs scored by V Kohli against JJ Bumrah
total_runs_by_kohli = filtered_df['total_runs'].sum()

# Display the result
print(f"Total runs scored by V Kohli when the bowler was JJ Bumrah: {total_runs_by_kohli}")

Total runs scored by V Kohli when the bowler was JJ Bumrah: 114

In [ ]:
# Caught and Bowled

In [36]:
# Filter the dataset for dismissals via "caught and bowled"
caught_and_bowled_df = ipl[ipl['dismissal_kind'] == 'caught and bowled']

# Group by player and count the number of dismissals via "caught and bowled" for each player
dismissals_count = caught_and_bowled_df['player_dismissed'].value_counts().reset_index()

# Rename the columns for clarity
dismissals_count.columns = ['Player', 'Dismissals Count']

# Display the player with the maximum number of dismissals via "caught and bowled"
max_dismissals_player = dismissals_count.iloc[0]
print(f"The player dismissed the maximum number of times via 'caught and bowled' is {max_dismissals_player['Player']} with {max_dismissals_player['Dismissals Count']} dismissals.")

The player dismissed the maximum number of times via 'caught and bowled' is SK Raina with 7 dismissals.

In [ ]:
# Hard Hitting Player

In [27]:
highest_hard_hitting_player = ipl.loc[ipl['batsman'].argmax()]

# Display the result
print(f"The player with the highest hard-hitting ability is {highest_hard_hitting_player['player']} with a hard-hitting score of {highest_hard_hitting_player['hard_hitting_score']}.")

TypeError: reduction operation 'argmax' not allowed for this dtype

In [44]:
# Convert the column to numeric if it's not already
ipl['hard_hitting_score'] = pd.to_numeric(ipl['batsman'], errors='coerce')

# Find the player with the highest hard-hitting ability
highest_hard_hitting_player = ipl.loc[ipl['batsman'].idxmax()]

# Display the result
print(f"The player with the highest hard-hitting ability is {highest_hard_hitting_player['player']} with a hard-hitting score of {highest_hard_hitting_player['hard_hitting_score']}.")

TypeError: reduction operation 'argmax' not allowed for this dtype

In [34]:
ipl['dismissal_kind'].value_counts()

caught                   5348
bowled                   1581
run out                   852
lbw                       540
stumped                   278
caught and bowled         211
retired hurt               12
hit wicket                 10
obstructing the field       2
Name: dismissal_kind, dtype: int64